version: '3.8'

services:

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 4000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORT: 4000
      HOST: localhost
    ports:
      - 4000
    depends_on:
      - db